# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "ubuntu"
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder "./html/", "/var/www/html/"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "basic-apache-web-server"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello from the Vagrantfile"
  SHELL
end
