# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "ubuntu-vm" do |vm1|
        vm1.vm.hostname = "ubuntu-vm"
        vm1.vm.box      = "bento/ubuntu-20.04"
        vm1.vm.network "private_network", ip: "192.168.33.10"
        vm1.vm.provider "virtual-box" do |vb|
            vb.name     = "ubuntu-vm"
            vb.memory   = "1024"
        end
        
        vm1.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "Hello from the Ubuntu VM"
        SHELL
    end

    config.vm.define "centos-vm" do |vm2|
        vm2.vm.hostname = "centos-vm"
        vm2.vm.box      = "bento/centos-7.2"
        vm2.vm.network "private_network", ip: "192.168.33.20"
        vm2.vm.provider "virtual-box" do |vb|
            vb.name     = "centos-vm"
            vb.memory   = "1024"
        end
        
        vm2.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "Hello from the Centos VM"
        SHELL
    end
end